#include "enemies.h"

/*
 * The shared ranges come from the initial assignments in PRZEDM.TPU's eight
 * named combat procedures. Turbo Pascal Random(N) produces values 0..N-1.
 * The dogs use PRZEDM.TPU WALKAPIES. The five cage monsters use direct
 * assignments in their room handlers.
 */
static const EnemyProfile profiles[] = {
    {ENEMY_PROFILE_SLABO, "SLABO", {1, 1}, {2, 2}, {1, 1},
     {ENEMY_REWARD_STANDARD, {0, 2}, {0, 0}, {0, 0}, {0, 0}}},
    {ENEMY_PROFILE_MNIEJSLABO, "MNIEJSLABO", {34, 36}, {10, 10}, {8, 11},
     {ENEMY_REWARD_STANDARD, {10, 30}, {0, 0}, {0, 0}, {5, 20}}},
    {ENEMY_PROFILE_SREDNIO, "SREDNIO", {50, 54}, {13, 14}, {10, 14},
     {ENEMY_REWARD_STANDARD, {30, 59}, {0, 0}, {0, 0}, {7, 20}}},
    {ENEMY_PROFILE_TRUDNO, "TRUDNO", {60, 65}, {15, 17}, {12, 14},
     {ENEMY_REWARD_STANDARD, {20, 59}, {0, 0}, {0, 0}, {7, 20}}},
    {ENEMY_PROFILE_BTRUDNO, "BTRUDNO", {72, 74}, {16, 17}, {13, 14},
     {ENEMY_REWARD_STANDARD, {15, 64}, {0, 0}, {0, 0}, {5, 20}}},
    {ENEMY_PROFILE_VEASY, "VEASY", {90, 99}, {17, 18}, {14, 15},
     {ENEMY_REWARD_STANDARD, {10, 64}, {0, 0}, {0, 0}, {4, 20}}},
    {ENEMY_PROFILE_EASY, "EASY", {100, 119}, {18, 19}, {16, 16},
     {ENEMY_REWARD_STANDARD, {30, 59}, {0, 0}, {0, 0}, {4, 20}}},
    {ENEMY_PROFILE_NEASY, "NEASY", {130, 149}, {19, 20}, {20, 20},
     {ENEMY_REWARD_STANDARD, {20, 64}, {0, 0}, {0, 0}, {4, 20}}},
    {ENEMY_PROFILE_POKRZYWA, "direct cave assignment", {200, 200}, {18, 18},
     {15, 15}, {ENEMY_REWARD_NONE, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, 5, 1},
    {ENEMY_PROFILE_QUEST_MASTER, "direct room assignment", {188, 188},
     {10, 10}, {26, 26},
     {ENEMY_REWARD_NONE, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, 20, 10},
    {ENEMY_PROFILE_DOG, "WALKAPIES", {10, 10}, {5, 5}, {10, 10},
     {ENEMY_REWARD_DOG, {0, 14}, {0, 0}, {0, 0}, {5, 20}}},
    {ENEMY_PROFILE_CAGE_WEAK, "direct room assignment", {20, 20}, {3, 3}, {3, 3},
     {ENEMY_REWARD_CAGE, {0, 9}, {4, 20}, {4, 20}, {6, 20}}},
    {ENEMY_PROFILE_CAGE_DEXTEROUS, "direct room assignment", {20, 20}, {3, 3}, {30, 30},
     {ENEMY_REWARD_CAGE, {0, 14}, {7, 20}, {7, 20}, {6, 20}}},
    {ENEMY_PROFILE_CAGE_RESISTANT, "direct room assignment", {40, 40}, {3, 3}, {3, 3},
     {ENEMY_REWARD_CAGE, {0, 14}, {7, 20}, {7, 20}, {6, 20}}},
    {ENEMY_PROFILE_CAGE_STRONG, "direct room assignment", {20, 20}, {10, 10}, {3, 3},
     {ENEMY_REWARD_CAGE, {0, 14}, {7, 20}, {7, 20}, {6, 20}}},
    {ENEMY_PROFILE_CAGE_ALL, "direct room assignment", {40, 40}, {10, 10}, {11, 11},
     {ENEMY_REWARD_CAGE, {0, 29}, {10, 20}, {10, 20}, {6, 20}}}
};

static const EnemyProfileId actor_profiles[WORLD_ACTOR_COUNT] = {
    [WORLD_ACTOR_KORNIK] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_MUCHA] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_BAKTERIA] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_SLIMAK] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_ZUK] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_KARALUCH] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_MROWKA] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_PAJAK] = ENEMY_PROFILE_SLABO,

    [WORLD_ACTOR_DZIK] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_SZCZUR] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_LIS] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_KUROPATWA] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_ZAJAC] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_WILCZUR] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_ORZEL] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_SARNA] = ENEMY_PROFILE_MNIEJSLABO,

    [WORLD_ACTOR_SLON] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_LEW] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_ZYRAFA] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_WIELBLAD] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_STRUS] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_BOA] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_WILK] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_BIZON] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_PANTERA] = ENEMY_PROFILE_SREDNIO,

    [WORLD_ACTOR_GLADIATOR] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_WOJOWNIK] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_TRENER] = ENEMY_PROFILE_TRUDNO,

    [WORLD_ACTOR_JAMNIK] = ENEMY_PROFILE_DOG,
    [WORLD_ACTOR_OWCZAREK] = ENEMY_PROFILE_DOG,
    [WORLD_ACTOR_SPANIEL] = ENEMY_PROFILE_DOG,
    [WORLD_ACTOR_PUDEL] = ENEMY_PROFILE_DOG,
    [WORLD_ACTOR_PIESEK] = ENEMY_PROFILE_DOG,

    [WORLD_ACTOR_TAKSOWKARZ] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_SPRZEDAWCA_PRECELKOW] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_ZAMIATACZ] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_PIJAK] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_ZEBRAK] = ENEMY_PROFILE_VEASY,

    [WORLD_ACTOR_GITARZYSTA] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_PERKUSISTA] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_ORGANISTA] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_LIROY] = ENEMY_PROFILE_NEASY,

    [WORLD_ACTOR_DZIECKO] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_WARIAT] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_SLUCHACZ] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_FAN] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_CZLOWIEK] = ENEMY_PROFILE_SREDNIO,
    [WORLD_ACTOR_POLICJANT] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_OCHRONIARZ] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_GORYL] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_DZIADEK] = ENEMY_PROFILE_MNIEJSLABO,
    [WORLD_ACTOR_REPORTER] = ENEMY_PROFILE_SREDNIO,

    [WORLD_ACTOR_SZCZAW] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_STOKROTKA] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_KONICZYNKA] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_MLECZ] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_DMUCHAWIEC] = ENEMY_PROFILE_VEASY,
    [WORLD_ACTOR_ROZA] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_JEZYNA] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_OSET] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_AGREST] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_MALINA] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_TRAWA] = ENEMY_PROFILE_TRUDNO,
    [WORLD_ACTOR_DUNCAN] = ENEMY_PROFILE_EASY,
    [WORLD_ACTOR_POKRZYWA] = ENEMY_PROFILE_POKRZYWA,
    [WORLD_ACTOR_STARUCH] = ENEMY_PROFILE_SLABO,
    [WORLD_ACTOR_QUEST_MASTER] = ENEMY_PROFILE_QUEST_MASTER,
    [WORLD_ACTOR_LIVING_DOOR] = ENEMY_PROFILE_NEASY,

    [WORLD_ACTOR_CAGE_WEAK] = ENEMY_PROFILE_CAGE_WEAK,
    [WORLD_ACTOR_CAGE_DEXTEROUS] = ENEMY_PROFILE_CAGE_DEXTEROUS,
    [WORLD_ACTOR_CAGE_RESISTANT] = ENEMY_PROFILE_CAGE_RESISTANT,
    [WORLD_ACTOR_CAGE_STRONG] = ENEMY_PROFILE_CAGE_STRONG,
    [WORLD_ACTOR_CAGE_ALL] = ENEMY_PROFILE_CAGE_ALL
};

_Static_assert(
    sizeof(profiles) / sizeof(profiles[0]) == ENEMY_PROFILE_COUNT - 1,
    "every valid enemy profile needs a definition"
);
_Static_assert(
    sizeof(actor_profiles) / sizeof(actor_profiles[0]) == WORLD_ACTOR_COUNT,
    "every world actor needs an enemy profile slot"
);

size_t enemy_profile_count(void)
{
    return sizeof(profiles) / sizeof(profiles[0]);
}

const EnemyProfile *enemy_profile_at(size_t index)
{
    if (index >= enemy_profile_count()) {
        return NULL;
    }
    return &profiles[index];
}

const EnemyProfile *enemy_profile_find(EnemyProfileId id)
{
    if (id <= ENEMY_PROFILE_INVALID || id >= ENEMY_PROFILE_COUNT) {
        return NULL;
    }
    return &profiles[(size_t)id - 1];
}

EnemyProfileId enemy_profile_for_world_actor(WorldActorId actor)
{
    if (actor < 0 || actor >= WORLD_ACTOR_COUNT) {
        return ENEMY_PROFILE_INVALID;
    }
    return actor_profiles[actor];
}
