#include "world.h"

#define ARENA_DESCRIPTION "JESTES NA ARENIE I CZUJESZ POTRZEBE ZABIJANIA"
#define ARENA_EXIT(direction, destination) {direction, destination}
#define ARENA_ROOM(room_id, exit_text, number_of_exits, ...) \
    {room_id, "Arena", ARENA_DESCRIPTION, exit_text, NULL, NULL, {__VA_ARGS__}, number_of_exits}

/*
 * Player-facing strings below were copied from Pascal short strings in the
 * original artifacts and transcoded from CP852 to UTF-8. Preserve wording,
 * grammar, punctuation, capitalization, and oddities. Only spelling corrections
 * recorded in docs/compatibility.md are allowed. Unrecovered text must use a
 * conspicuous [PORT: ...] marker.
 */
static const Room rooms[] = {
    {
        ROOM_START,
        "Miejsce rozpoczecia gry",
        "TU ZACZYNA SIE GRE",
        "DOSTEPNE WYJSCIE-POLNOC-HALA GLOWNA MUD SZKOLE ",
        NULL,
        NULL,
        {{DIRECTION_NORTH, ROOM_CENTRAL}},
        1
    },
    {
        ROOM_CENTRAL,
        "Pokoj centralny",
        "JESTES W OKROGLYM SALONIE WYPELNIONYM WITRAZAMI \n"
        "W POWIETRZU UNOSZA SIE ZAPACHY I SA TO ZAPACHY OK\n"
        "NO A POZA TYM NA SCIANIE JEST!!! PLAKAT!!!!\n"
        "NAPISZ PATRZ PLAKAT ABY GO ODCZYTAĆ ",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-TAM GDZIE ZACZYNASZ GRE\n"
        "POLNOC-MIASTO\n"
        "WSCHOD-POKOJ TRENINGOWY 1\n"
        "ZACHOD-MUD SZKOLA\n"
        "DOL-PODDZIEMNY POKOJ TRENINGOWY(2)",
        "PLAKAT",
        "NA PLAKACIE PISZE:\n"
        "JEŻELI CHCESZ TRENOWAC UDAJ SIE DO POKOJU TRENINGOWEGO\n"
        "JEŻELI CHCESZ NAUCZYC SIE NOWYCH KOMEND IDZ DO MUD SZKOLY\n"
        "DOPIERO POTEM IDZ DO MIASTA \n"
        "A OTO TAJNE KOMENDY :\n"
        " WSZYSTKO DZIALA OD RAZU , NIE MUSISZ WCHODZIC W ZADEN DZIWNY STAN\n"
        " JA - WSZYSTKO O TOBIE , BIERZ , UZYJ , ZDEJMIJ , ODRZUC I INNE \n"
        " PATRZ PLAKAT I NA ARENIE PISZ KTO - BO TAM NIE JESTES SAM\n"
        " CWICZ KOPAC , UCIEKAC , POROWNANIE I INNE JAK BEDZIESZ KOZAK\n"
        " UWAGA Z OSTATNIEJ CHWILI : SPIJ KIEDY CHCESZ , NIKT CIE NIE PILNUJE!",
        {
            {DIRECTION_SOUTH, ROOM_START},
            {DIRECTION_NORTH, ROOM_CITY_THRESHOLD},
            {DIRECTION_EAST, ROOM_TRAINING},
            {DIRECTION_WEST, ROOM_SCHOOL},
            {DIRECTION_DOWN, ROOM_UNDERGROUND}
        },
        5
    },
    {
        ROOM_SCHOOL,
        "Hala MUD szkoly",
        "JESTES W HALLU MUD SZKOLY- OGARNIA CIE CYKORIA  \n"
        "NO A POZA TYM NA SCIANIE JEST!!! AFISZ!!!",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-POKOJ CENTRALNY\n"
        "ZACHOD-MUD SZKOLA (2)",
        "AFISZ",
        "NA AFISZU BYNAJMNIEJ PISZE\n"
        "TO JEST MUD SZKOLA KUJ KOMENDY ALBO ZGINIESZ!!!!!!!!\n"
        "JESLI CHODZI O EKWIPUNEK TO BIERZ (PRZEDMIOT)=BIERZESZ PRZEDMIOT\n"
        "UZYJ (PRZEDMIOT) = UZYWASZ PRZEDMIOTU ODRZUC (PRZEDMIOT) = ODRZUCASZ\n"
        "BRONIE I TARCZE I UBRANIA MOZNA ZDJAC KOMENDA ODLOZ (PRZEDMIOT) ",
        {
            {DIRECTION_EAST, ROOM_CENTRAL},
            {DIRECTION_WEST, ROOM_SCHOOL_TWO}
        },
        2
    },
    {
        ROOM_SCHOOL_TWO,
        "MUD Szkola (2)",
        "SZOK!! AAA UPSI  O NIE FUJ ACH AJ OCH NEIN EEE UGH   \n"
        "STWIERDZASZ ZE W TYM POKOJU JEST X POKOI O NIE !! JAK SIE WYDOSTAC?\n"
        "AHA (NA SCIANIE JEST PLAKAT)",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-MUD SZKOLA\n"
        "ZACHOD-POKOJ\n"
        "POLNOC-POKOJ\n"
        "POLUDNIE-POKOJ\n"
        "GORA-POKOJ\n"
        "DOL-POKOJ",
        "PLAKAT",
        "NA PLAKACIE BYNAJMNIEJ PISZE\n"
        "TO JEST POKOJ DO ORIETACJI W TERENIE ORAZ W KIERUNKACH",
        {
            {DIRECTION_EAST, ROOM_SCHOOL},
            {DIRECTION_WEST, ROOM_SCHOOL_WEST_ROOM},
            {DIRECTION_NORTH, ROOM_SCHOOL_NORTH_ROOM},
            {DIRECTION_SOUTH, ROOM_SCHOOL_SOUTH_ROOM},
            {DIRECTION_UP, ROOM_SCHOOL_UP_ROOM},
            {DIRECTION_DOWN, ROOM_SCHOOL_DOWN_ROOM}
        },
        6
    },
    {
        ROOM_SCHOOL_WEST_ROOM,
        "Pokoj 6",
        "JESTES W DOSYC CIASNYM POKOJU I NICZEGO TU NIEMA ",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-MUD SZKOLA(2)",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_SCHOOL_TWO}},
        1
    },
    {
        ROOM_SCHOOL_NORTH_ROOM,
        "Pokoj 7",
        "JESTES W DOSYC CIASNYM POKOJU I NICZEGO TU NIEMA ",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-MUD SZKOLA(2)",
        NULL,
        NULL,
        {{DIRECTION_SOUTH, ROOM_SCHOOL_TWO}},
        1
    },
    {
        ROOM_SCHOOL_SOUTH_ROOM,
        "Pokoj 8",
        "JESTES W DOSYC CIASNYM POKOJU I NICZEGO TU NIEMA ",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-MUD SZKOLA(2)",
        NULL,
        NULL,
        {{DIRECTION_NORTH, ROOM_SCHOOL_TWO}},
        1
    },
    {
        ROOM_SCHOOL_UP_ROOM,
        "Pokoj 9",
        "JESTES W MALUTKIM POKOJU ALE WIDZISZ WYJSCIA W DWIE STRONY \n"
        "SKADS SLYSZYSZ DZIWNE NIEPOKOJACE WRZASKI",
        "DOSTEPNE WYJSCIA:\n"
        "DOL-MUD SZKOLA (2)\n"
        "GORA-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {
            {DIRECTION_DOWN, ROOM_SCHOOL_TWO},
            {DIRECTION_UP, ROOM_CAGE_HALL}
        },
        2
    },
    {
        ROOM_SCHOOL_DOWN_ROOM,
        "Pokoj 10",
        "JESTES W DOSYC CIASNYM POKOJU I NICZEGO TU NIEMA ",
        "DOSTEPNE WYJSCIA:\n"
        "GORA-MUD SZKOLA(2)",
        NULL,
        NULL,
        {{DIRECTION_UP, ROOM_SCHOOL_TWO}},
        1
    },
    {
        ROOM_CAGE_HALL,
        "Klatki pelne gajdy",
        "JESTES W POKOJU PROWADZACYM DO KLATEK\n"
        "DRZWI POD TOBA SIE ZATRZASNELY I NIE MASZ ODWROTU\n"
        "WE WSZYSTKICH KIERUNKACH SA KLATKI I UJADAJACE SIE W NICH POTWORY\n"
        "NO A POZA TYM NA SCIANIE JEST!!! PLAKAT!!!!",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-KLATKA CIENIASA\n"
        "ZACHOD-KLATKA SILNEGO\n"
        "POLNOC-KLATKA ZRECZNEGO\n"
        "POLUDNIE-KLATKA ODPORNEGO\n"
        "GORA-KLATKA SILNEGO,ODPORNEGO I ZRECZNEGO \n"
        "DOL-JEDYNA DROGA NIE PROWADZACA DO KLATEK",
        "PLAKAT",
        "NA PLAKACIE PISZE:\n"
        "W KLATKACH SA POTWORKI - ZABIJ JE! KOMEDA : ZABIJ [COS] - ZABIJA \n"
        "CZASAMI COS WYPADNIE Z POTWORKA MOZE CI SIE TO PRZYDAC",
        {
            {DIRECTION_EAST, ROOM_CAGE_WEAK},
            {DIRECTION_WEST, ROOM_CAGE_STRONG},
            {DIRECTION_NORTH, ROOM_CAGE_DEXTEROUS},
            {DIRECTION_SOUTH, ROOM_CAGE_RESISTANT},
            {DIRECTION_UP, ROOM_CAGE_ALL},
            {DIRECTION_DOWN, ROOM_TELEPORT}
        },
        6
    },
    {
        ROOM_CAGE_WEAK,
        "Klatka cieniasa",
        "TEN POKOJ JEST CALY OBRYZGANY KRWIA NA SCIANACH FLAKI I MOZGI LODZKIE ",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {{DIRECTION_WEST, ROOM_CAGE_HALL}},
        1
    },
    {
        ROOM_CAGE_DEXTEROUS,
        "Klatka zrecznego",
        "TEN POKOJ JEST CALY OBRYZGANY KRWIA NA SCIANACH FLAKI I MOZGI LODZKIE ",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {{DIRECTION_SOUTH, ROOM_CAGE_HALL}},
        1
    },
    {
        ROOM_CAGE_RESISTANT,
        "Klatka odpornego",
        "TEN POKOJ JEST CALY OBRYZGANY KRWIA NA SCIANACH FLAKI I MOZGI LODZKIE ",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {{DIRECTION_NORTH, ROOM_CAGE_HALL}},
        1
    },
    {
        ROOM_CAGE_STRONG,
        "Klatka silnego",
        "TEN POKOJ JEST CALY OBRYZGANY KRWIA NA SCIANACH FLAKI I MOZGI LODZKIE ",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_CAGE_HALL}},
        1
    },
    {
        ROOM_CAGE_ALL,
        "Klatka silnego, odpornego i zrecznego",
        "TEN POKOJ JEST CALY OBRYZGANY KRWIA NA SCIANACH FLAKI I MOZGI LODZKIE ",
        "DOSTEPNE WYJSCIA:\n"
        "DOL-KLATKI PELNE GAJDY",
        NULL,
        NULL,
        {{DIRECTION_DOWN, ROOM_CAGE_HALL}},
        1
    },
    {
        ROOM_TELEPORT,
        "Teleport",
        "JESTES W POKOJU W KTORYM !JEST! !PLAKAT (SMIERDZI TU) ",
        "DOSTEPNE WYJSCIA:\n"
        "GORA-KLATKI PELNE GAJDY\n"
        "DOL-TELEPORT!!!",
        "PLAKAT",
        "NA PLAKACIE PISZE:\n"
        "SORRY ZE NIE UMYLEM POKOJU ALE NIE MAM NA TO CZASU\n"
        "JEZELI BYLES AKTYWNY TO POWINIENES LICZYC NA NAGRODE\n"
        "SPRAWDZ CZY LEZY TU COS , POTEM MOZESZ ZEJZD DO TELEPORTU ",
        {
            {DIRECTION_UP, ROOM_CAGE_HALL},
            {DIRECTION_DOWN, ROOM_TELEPORT_EFFECT}
        },
        2
    },
    {
        ROOM_TELEPORT_EFFECT,
        "Teleport",
        "BBBBBBBBZBZBZBZBZZZZZZZzzzzzzzzzbbzbBbzbzbzBZZZ\n"
        "===-------......_________.....----------....._______....-------======\n"
        "T***E***L***E***P***O***R***T***O***W***A***L***E***S***** *****S***I***E!\n"
        "==========================================================================",
        "",
        NULL,
        NULL,
        {{DIRECTION_NONE, ROOM_START}},
        0,
        NULL,
        NULL,
        true,
        ROOM_CENTRAL
    },
    {
        ROOM_TRAINING,
        "Pokoj treningowy",
        "JESTES W POKOJU GDZIE RAMBO TRENUJE SWYCH UCZNOW \n"
        "WSZĘDZIE SĄ PRZEDMIOTY DO RÓŻNYCH RODZAJI ĆWICZEŃ\n"
        "NO A POZA TYM NA SCIANIE JEST!!! PLAKAT!!!!",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-POKÓJ CENTRALNY",
        "PLAKAT",
        "NA PLAKACIE PISZE:\n"
        "ABY TRENOWAĆ UŻYJ KOMENDY TRENUJ RAZEM Z \n"
        "SILA , ZRECZNOSC  LUB MADROSC ",
        {{DIRECTION_WEST, ROOM_CENTRAL}},
        1
    },
    {
        ROOM_CITY_THRESHOLD,
        "MIASTO",
        "JESTES W CENTRUM MIASTA : NA SCIANIE JEST PLAKAT (DUZY RUCH) ",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-POKOJ CENTRALNY\n"
        "POLNOC-UL.SKLEPIKOWA\n"
        "WSCHOD-UL.CIEMNA\n"
        "ZACHOD-UL.DLUGA",
        "PLAKAT",
        "TO JEST MIASTO : RADZ SOBIE SAM!",
        {{DIRECTION_SOUTH, ROOM_CENTRAL},
         {DIRECTION_NORTH, ROOM_SHOP_STREET},
         {DIRECTION_EAST, ROOM_DARK_STREET},
         {DIRECTION_WEST, ROOM_LONG_STREET}},
        4
    },
    {
        ROOM_SHOP_STREET,
        "Ulica sklepikowa",
        "JESTES NA ULICY NA ULICY SKLEPIKOWEJ - JAK SAMA NAZWA WZKAZUJE  \n"
        "JEST TU PARE SKLEPIKOW KTORE BYC MOZE CI SIE PRZYDADZA",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-CENTRUM MIASTA\n"
        "POLNOC-UL.SKLEPIKOWA\n"
        "WSCHOD-PIEKARNIA\n"
        "ZACHOD-ZBROJOWNIA",
        NULL,
        NULL,
        {{DIRECTION_SOUTH, ROOM_CITY_THRESHOLD},
         {DIRECTION_NORTH, ROOM_SHOP_STREET_NORTH},
         {DIRECTION_EAST, ROOM_BAKERY},
         {DIRECTION_WEST, ROOM_ARMORY}},
        4
    },
    {
        ROOM_SHOP_STREET_NORTH,
        "Ulica sklepikowa",
        "CIAGNIE SIE TEDY ULICA SKLEPIKOWA JEST TU JESZCZE PARE  \n"
        "INTERESUJACYCH SKLEPOW. DALEJ CIAGNIE SIE KILKA ULIC....",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-UL.SKLEPIKOWA\n"
        "POLNOC-ROZJAZD!\n"
        "WSCHOD-SKLEP WIELOBRANZOWY\n"
        "ZACHOD-SKLEP MAGICZNY  ",
        NULL,
        NULL,
        {
            {DIRECTION_SOUTH, ROOM_SHOP_STREET},
            {DIRECTION_NORTH, ROOM_JUNCTION},
            {DIRECTION_EAST, ROOM_GENERAL_STORE},
            {DIRECTION_WEST, ROOM_MAGIC_STORE}
        },
        4
    },
    {
        ROOM_GENERAL_STORE,
        "Sklep wielobranzowy",
        "WSZEDLES DO SKLEPU WIELOBRANZOWEGO,STWIERDZASZ OBECNOSC SPRZEDAWCY\n"
        "NA DRZWIACH ZOSTALA WYWIESZONA WYWIESZKA",
        "DOSTEPNE WYJSCIA:\n"
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-ULICA SKLEPIKOWA",
        "WYWIESZKA",
        "* SKLEP OTWARTY DO ODWOLANIA *",
        {{DIRECTION_WEST, ROOM_SHOP_STREET_NORTH}},
        1
    },
    {
        ROOM_MAGIC_STORE,
        "Sklep magiczny",
        "WCHODZISZ DO SKLEPU ALE NICZEGO TU NIE MA POZA SPRZEDAWCA I JEGO TOWAREM",
        "DOSTEPNE WYJSCIA:\n"
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-ULICA SKLEPIKOWA",
        "PLAKAT",
        "* OTWARTE Z POWODU CHOROBY *",
        {{DIRECTION_EAST, ROOM_SHOP_STREET_NORTH}},
        1
    },
    {
        ROOM_BAKERY,
        "Piekarnia",
        "JESTES W PIEKARNI , SKLEP PRZESIAKNIETY JEST PRZYJEMNYM ZAPACHEM CHLEBA \n"
        "PIEKARZ MILO SIE NA CIEBIE PATRZY WYCIERAJAC MAKE Z TWARZY\n"
        "NA SCIANIE  JEST PLAKAT CALY W MACE",
        "ZACHOD-ULICA SKLEPIKOWA",
        "PLAKAT",
        "LISTA-LISTA DOSTEPNYCH RZECZY,KUP (PRZEDMIOT)-KUPUJESZ GO \n"
        "PO ODEJSCIU OD LADY REKLAMACJI NIE UWZGLEDNIA SIE",
        {{DIRECTION_WEST, ROOM_SHOP_STREET}},
        1
    },
    {
        ROOM_ARMORY,
        "Zbrojownia",
        "JESTES W ZBROJOWNI - SKLEP NIEDAWNO ZOSTAL OTWARTY\n"
        "SPRZEDAWCA(BRZYDKA AURA) STARA SIE WCISNAC CI JAKIS TOWAR \n"
        "NA SCIANIE WISI PLAKAT",
        "WSCHOD-ULICA SKLEPIKOWA",
        "POSTER",
        "OKAZJA !!! PRZY ZAKUPIE GARNITURU KOMPLET UBRAN GRATIS !!!(ZART)",
        {{DIRECTION_EAST, ROOM_SHOP_STREET}},
        1
    },
    {
        ROOM_DARK_STREET,
        "Ulica ciemna",
        "JESTES NA ULICY CIEMNEJ , WLASCIWIE NARAZIE NIE JEST TU JESZCZE TAK CIEMNO \n"
        "TA ULICA WYGLADA NA REMONTOWANĄ , NA POLNOC WIDZISZ JAKIS BAR\n"
        "NA POLUDNIE PRZEBIEGAJA CIE DRESZCZE , JEST TAM NAPRAWDE CIEMNO",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-CENTRUM MIASTA\n"
        "POLNOC-BAR POD DWOMA PEDALAMI\n"
        "POLUDNIE-BLUSZCZ",
        NULL,
        NULL,
        {{DIRECTION_WEST, ROOM_CITY_THRESHOLD},
         {DIRECTION_NORTH, ROOM_BAR},
         {DIRECTION_SOUTH, ROOM_BRUSZCZ}},
        3
    },
    {
        ROOM_BAR,
        "Bar pod dwoma pedalami",
        "JESTES W BARZE POD DWOMA PEDALAMI CHCAC ROZWIKLAC TA DZIWNA NAZWE\n"
        "PYTASZ SIE BARMANA : PRZEPRASZAM DLACZEGO TEN BAR NAZYWA SIE  \n"
        "\"POD DWOMA PEDALAMI\"? A ON NA TO -WLASCIWIE TO NIE WIEM\n"
        " ALE SPYTAM SIE ZONY:MAREEEK!!.......(teraz już wiesz) \n"
        "MACIEK , TUTEJSZY BARMAN SERWUJE TUTAJ DRINKI (MOZLIWA LISTA!\n"
        " PEDAL CZEKA TU NA TEGO JEDYNEGO\n"
        "PARA-JACEK I JUREK OBMYSLAJA MIESIAC MIODOWY",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-ULICA CIEMNA",
        NULL,
        NULL,
        {{DIRECTION_SOUTH, ROOM_DARK_STREET}},
        1
    },
    {
        ROOM_BRUSZCZ,
        "Bluszcz",
        "ZNALAZLES SIE WSROD BLUSZCZU , WOKOLO CIEBIE TAJEMNICZE ROSLINY \n"
        "MUSISZ BARDZO UWAZAC,TU NAWET STOKROTKA MOZE BYC ZABOJCZA",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-UL.CIEMNA\n"
        "WSCHOD-BLUSZCZ\n"
        "ZACHOD-BLUSZCZ\n"
        "POLUDNIE-BLUSZCZ",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_DARK_STREET},
            {DIRECTION_EAST, ROOM_BRUSZCZ_EAST},
            {DIRECTION_WEST, ROOM_BRUSZCZ_WEST},
            {DIRECTION_SOUTH, ROOM_BRUSZCZ_SOUTH}
        },
        4
    },
    {
        ROOM_BRUSZCZ_EAST,
        "Bluszcz",
        "WSZEDLES W GASZCZ ROSLIN I KWIATOW\n"
        "NIE MA CO OPISYWAC WYSTARCZY POWIEDZIEC ZE JEST TU BYDLO CHWASTOW",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-BLUSZCZ",
        NULL,
        NULL,
        {{DIRECTION_WEST, ROOM_BRUSZCZ}},
        1
    },
    {
        ROOM_BRUSZCZ_WEST,
        "Bluszcz",
        "SLYSZYSZ POKRZYWE KTORA POZERA BEZBRONNY SZCZAW .... OHYDA\n"
        "WOKOLO TAK CIEMNO,ZE GDYBY NIE JA JUZ DAWNO BYS ZGINA",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-BLUSZCZ",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_BRUSZCZ}},
        1
    },
    {
        ROOM_BRUSZCZ_SOUTH,
        "Bluszcz",
        "CHOC TO MALO PRAWDOPODOBNE TUTAJ JEST JESZCZE CIEMNIEJ\n"
        "PONADTO W NIEKTORYCH MIEJSCACH ZNAJDUJE SIE BLOTO I INNE BZDURY\n"
        "NA SRODKU ZNAJDUJE SIE STUDNIA I MALO CZYTELNY NAPIS",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-BLUSZCZ\n"
        "WSCHOD-BLUSZCZ\n"
        "ZACHOD-BLUSZCZ\n"
        "POLUDNIE-BLUSZCZ",
        "NAPIS",
        "PISZE TUTAJ : \x02" "A\x02RZY\x02 D\x02 S\x02UDN\x02 (MOWILEM ZE MALO CZYTELNY)",
        {
            {DIRECTION_NORTH, ROOM_BRUSZCZ},
            {DIRECTION_EAST, ROOM_BRUSZCZ_SOUTH_EAST},
            {DIRECTION_WEST, ROOM_BRUSZCZ_SOUTH_WEST},
            {DIRECTION_SOUTH, ROOM_FOREST}
        },
        4,
        "STUDNIA",
        NULL
    },
    {
        ROOM_BRUSZCZ_SOUTH_WEST,
        "Bluszcz",
        "PRZEDZIERASZ SIE PRZEZ CALY TEN SYF I NAJCHETNIEJ BYS\n"
        "TERAZ PORZYCZYŁ KOSIARKI OD SWEGO KOLEGI TOMKA",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-BLUSZCZ",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_BRUSZCZ_SOUTH}},
        1
    },
    {
        ROOM_BRUSZCZ_SOUTH_EAST,
        "Bluszcz",
        "W TEJ KOMNACIE JEST ZNACZNIE JASNIEJ A TO DLATEGO ZE NAPROMIENIOWANE\n"
        "I ZMUTOWANE ROSLINY IDĄ W TWYM KIERUNKU",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-BLUSZCZ",
        NULL,
        NULL,
        {{DIRECTION_WEST, ROOM_BRUSZCZ_SOUTH}},
        1
    },
    {
        ROOM_LONG_STREET,
        "Ulica dluga",
        "ULICA DLUGA CIAGNIE SIE W NIESKONCZONOSC,SORKI\n"
        "NA POLNOCY ZNAJDUJESZ OGROMNA BUDOWLE=TO ARENA PRZEZNACZONA DO WALKI",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-CENTRUM MIASTA\n"
        "ZACHOD-ULICA DLUGA\n"
        "POLNOC-WEJSCIE NA ARENE",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_CITY_THRESHOLD},
         {DIRECTION_NORTH, ROOM_ARENA_ENTRANCE},
         {DIRECTION_WEST, ROOM_LONG_STREET_WEST}},
        3
    },
    {
        ROOM_LONG_STREET_WEST,
        "Ulica dluga",
        "IDAC ULICA DLUGA NA POLNOC SPOSTRZEGASZ DOLINE ROZRYWEK\n"
        "A NA POLUDNIE BASNIOWY GAJ...........",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-ULICA DLUGA\n"
        "POLNOC-DOLINA ROZRYWEK",
        NULL,
        NULL,
        {
            {DIRECTION_EAST, ROOM_LONG_STREET},
            {DIRECTION_NORTH, ROOM_ENTERTAINMENT_VALLEY}
        },
        2
    },
    {
        ROOM_ROAD,
        "Droga",
        "IDZIESZ DROGA , MIASTA PO DRODZE MIJASZ DROGOWSKAZ . JEST TU O WIELE \n"
        "NIEBEZPIECZNIEJ NIZ W MIESCIE PELNO TU ZEZIMIERZKOW ROZNEGO RODZAJU\n"
        "JESLI NIE CHCESZ MIEC KLOPOTOW LEPIEJ DOBRZE TRYMAJ SIE DROGI....",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-ROZJAZD!\n"
        "ZACHOD-DROGA\n"
        "POLNOC-LAS\n"
        "POLUDNIE-LAS",
        "DROGOWSKAZ",
        "WSCHOD - MIASTO , ZACHOD - SHIGGHLERATHR",
        {{DIRECTION_EAST, ROOM_JUNCTION},
         {DIRECTION_WEST, ROOM_STONY_ROAD}},
        2
    },
    {
        ROOM_JUNCTION,
        "Rozjazd",
        "ZNALAZLES SIE NA ROZJEZDZIE DROG , DROGI PILNUJE QUEST-MASTER \n"
        "QUEST-MASTER NIE POSCI CIE DALEJ DOPOKI NIE KUPISZ I ROZWIAZESZ QUESTA",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-UL.SKLEPIKOWA\n"
        "WSCHOD-DROGA O KTOREJ MOZESZ POMAZYC ( BO JEST W PRODUKCJI !!! )\n"
        "ZACHOD-DROGA ( ZABLOKOWANA PRZEZ QUEST-MASTERA)",
        NULL,
        NULL,
        {{DIRECTION_SOUTH, ROOM_SHOP_STREET_NORTH}},
        1
    },
    {
        ROOM_FOREST,
        "Las",
        "............................. PIERDUT...........PIERDUT......PIERDUT\n"
        "DOPIERO TERAZ SIE ZORIENTOWALES ZE NA SRODKU STOI WIELKIE DRZEWO\n"
        "HMMM ALE ZARAZ ... TE KRZAKI NA ZACHOD WYGLADAJA BARDZO PODEJRZANIE....",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-BLUSZCZ\n"
        "ZACHOD-PODEJRZANE KRZAKI",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_BRUSZCZ_SOUTH},
            {DIRECTION_WEST, ROOM_FOREST_WEST}
        },
        2
    },
    {
        ROOM_FOREST_WEST,
        "Podejrzane krzaki",
        "TO CIEKAWE ZE WCZESNIEJ NIE ZAUWAZYLES TYCH KRARZAKOW PRZEDZIERASZ\n"
        "SIE PRZEZ ICH GASZCZ WYGLADA TO NA NIEZBYT MILA KRAINE\n"
        "DALES NA ZACHOD WIDZISZ JAKIES PODEJRZANE BUDOWLE , A NA POLUDNIE BRRRR.\n"
        "NA POLUDNIE JAK GDYBY KTOS SIE OBZERAL , ALE BARDZO GLOSNO I NIEBEZPIECZNIE",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-BLUSZCZ\n"
        "ZACHOD-BUDYNEK\n"
        "POLUDNIE-WEJSCIE DO GROTY ",
        NULL,
        NULL,
        {
            {DIRECTION_EAST, ROOM_FOREST},
            {DIRECTION_WEST, ROOM_LIVING_DOOR},
            {DIRECTION_SOUTH, ROOM_CAVE_ENTRANCE}
        },
        3
    },
    {
        ROOM_LIVING_DOOR,
        "Budynek",
        "DO DOBRA WYGLADA TO NA JAKIS DOM , WEJDZMY DO SRODKA \n"
        "GOD DAMN , A NIECH MNIE MA MATEUSZ W SWOJEJ OPIECE , TE DRZWI ZYJA !!!",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-PODEJRZANE KRZAKI\n"
        "ZACHOD-GDYBY NIE TE CHOLERNE DRZWI ... ",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_FOREST_WEST}},
        1
    },
    {
        ROOM_ELF_HOUSE,
        "Domek",
        "DOBRA JESTES W SRODKU BRAK OSWIETLENIA CIE NIE WZRUSZA , DOOKOLA ROZNE GARNKI",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-BUDYNEK",
        "GARNKI",
        "Z JEZOREM NA WIERZCHU PATRZYSZ DO GARNKOW LECZ NIC W NICH NIE MA",
        {{DIRECTION_EAST, ROOM_LIVING_DOOR}},
        1
    },
    {
        ROOM_CAVE_ENTRANCE,
        "Wejscie do groty",
        "MLASK , MLASK KTOS RZECZYWISCIE SIE OBZERA CZY JESTES 100% PEWNY IZ\n"
        "CHCESZ SIE ZAGLEBIC W TE NIEBADANE CZELUSCIE PIEKIELNE?, MOZE LEPIEJ WROC\n"
        "NO PIEKNIE WLAZLES W JAKIES TOKSYCZNE SUBSTANCJE ,AAA, TO PARZY TRACISZ ",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-GROTA\n"
        "POLNOC-PODEJRZANE KRZAKI",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_FOREST_WEST},
            {DIRECTION_SOUTH, ROOM_CAVE}
        },
        2
    },
    {
        ROOM_CAVE,
        "Grota",
        "MOJ BOZE , COZ TO JEST , NA TRONIE SIEDZI 20 RAZY WIEKSZA OD CIEBIE POKRZYWA\n"
        "WOKOL NIEJ UWIJAJA SIE PRACOWITE MLECZE DOSTARCZAJAC JEJ SWIEZEGO \n"
        "MIESA LUDZKIEGO !!! , UWIELBIA ONA MOZGI KTORE WYSSYSA JAK PYSZNY PUDDING \n"
        "W PEWNYM MOMECIE ZAUWAZA CIEBIE - WITAJ WEDROWCZE PODOBAM CI SIE? - (TAK,NIE)",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-WEJSCIE DO GROTY",
        NULL,
        NULL,
        {{DIRECTION_NORTH, ROOM_CAVE_ENTRANCE}},
        1
    },
    {
        ROOM_STONY_ROAD,
        "Kamienista droga",
        "IDZIESZ DALEJ KAMIENISTA DROGA , BRZYDALA BI CI SIE JAKA BRYCZKA NALEPIEJ \n"
        "MODEL SZKAPA 2000 , ALE COZ KONIE SA TYLKO DLA NAJBOGATSZYCH",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-DROGA\n"
        "ZACHOD-DROGA\n"
        "POLNOC-LAS\n"
        "POLUDNIE-LAS",
        NULL,
        NULL,
        {
            {DIRECTION_EAST, ROOM_ROAD},
            {DIRECTION_WEST, ROOM_ROAD_END}
        },
        2
    },
    {
        ROOM_ROAD_END,
        "Droga",
        "CO TO ZA GLUPOTA ? DROGA SKRECA TROCHE W LEWO , TROCHE W PRAWO ALE \n"
        "PRZECIEZ ROWNIE DOBRZE MOGLA BY ISC SRODKIEM , ZYSKALI BY NA TYM WSZYSCY\n"
        "A SZCZEGOLNIE TY ,  BO BOLA CIE NOGI OD TEGO CHODZENIA NIEMOZEBNIE\n"
        "UPS DROGA SIE KONCZY NA TEJ NIEPRZEPASTNEJ RZECE O DALSZEJ PODROZY NIE MA MOWY",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-DROGA\n"
        "POLNOC-LAS\n"
        "POLUDNIE-LAS",
        NULL,
        NULL,
        {{DIRECTION_EAST, ROOM_STONY_ROAD}},
        1
    },
    {
        ROOM_ARENA_ENTRANCE,
        "Arena",
        "CZESC TO ARENA PRZYCHODZA TU TACY JAK TY PO TO ABY MORDOWAC\n"
        "!!!!!O NIE!!!!!!!! TO STRASZNE!!! ( SIE DAL NABRAC ) (NAPISZ PATRZ PLAKAT",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-ULICA DLUGA\n"
        "POLNOC-ARENA",
        "PLAKAT",
        "NA PLAKACIE PISZE\n"
        "NIE ATAKUJ LUDZI I ZWIERZAT Z ZOO CHYBA ZE MASZ 3 LEVEL( LUB WYZEJ :P)",
        {
            {DIRECTION_SOUTH, ROOM_LONG_STREET},
            {DIRECTION_NORTH, ROOM_ARENA_33}
        },
        2
    },
    ARENA_ROOM(
        ROOM_ARENA_33,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-WEJSCIE NA ARENE\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_ENTRANCE),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_34),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_35),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_36)
    ),
    ARENA_ROOM(
        ROOM_ARENA_34,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_33),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_37),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_38),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_39)
    ),
    ARENA_ROOM(
        ROOM_ARENA_35,
        "DOSTEPNE WYJSCIA:\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_38),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_40),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_33)
    ),
    ARENA_ROOM(
        ROOM_ARENA_36,
        "DOSTEPNE WYJSCIA:\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_39),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_33),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_41)
    ),
    ARENA_ROOM(
        ROOM_ARENA_37,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_34),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_42),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_43),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_44)
    ),
    ARENA_ROOM(
        ROOM_ARENA_38,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_35),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_43),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_45),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_34)
    ),
    ARENA_ROOM(
        ROOM_ARENA_39,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_36),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_44),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_34),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_46)
    ),
    ARENA_ROOM(
        ROOM_ARENA_40,
        "DOSTEPNE WYJSCIA:\nPOLNOC-ARENA\nZACHOD-ARENA",
        2,
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_45),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_35)
    ),
    ARENA_ROOM(
        ROOM_ARENA_41,
        "DOSTEPNE WYJSCIA:\nPOLNOC-ARENA\nWSCHOD-ARENA",
        2,
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_46),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_36)
    ),
    ARENA_ROOM(
        ROOM_ARENA_42,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_37),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_47),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_48),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_49)
    ),
    ARENA_ROOM(
        ROOM_ARENA_43,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_38),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_48),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_50),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_37)
    ),
    ARENA_ROOM(
        ROOM_ARENA_44,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_39),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_49),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_37),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_51)
    ),
    ARENA_ROOM(
        ROOM_ARENA_45,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_40),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_50),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_38)
    ),
    ARENA_ROOM(
        ROOM_ARENA_46,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nWSCHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_41),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_51),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_39)
    ),
    ARENA_ROOM(
        ROOM_ARENA_47,
        "MOZESZ ISC NA :\nPOLUDNIE-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_42),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_52),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_53)
    ),
    ARENA_ROOM(
        ROOM_ARENA_48,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_43),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_52),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_54),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_42)
    ),
    ARENA_ROOM(
        ROOM_ARENA_49,
        "DOSTEPNE WYJSCIA:\nPOLUDNIE-ARENA\nPOLNOC-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        4,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_44),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_53),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_42),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_55)
    ),
    ARENA_ROOM(
        ROOM_ARENA_50,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_45),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_54),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_43)
    ),
    ARENA_ROOM(
        ROOM_ARENA_51,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nWSCHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_46),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_55),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_44)
    ),
    ARENA_ROOM(
        ROOM_ARENA_52,
        "MOZESZ ISC NA :\nPOLUDNIE-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_48),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_56),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_47)
    ),
    ARENA_ROOM(
        ROOM_ARENA_53,
        "MOZESZ ISC NA :\nPOLUDNIE-ARENA\nWSCHOD-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_49),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_47),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_57)
    ),
    ARENA_ROOM(
        ROOM_ARENA_54,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nZACHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_50),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_56),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_48)
    ),
    ARENA_ROOM(
        ROOM_ARENA_55,
        "MOZESZ WYJSC NA :\nPOLNOC-ARENA\nPOLUDNIE-ARENA\nWSCHOD-ARENA",
        3,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_51),
        ARENA_EXIT(DIRECTION_NORTH, ROOM_ARENA_57),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_49)
    ),
    ARENA_ROOM(
        ROOM_ARENA_56,
        "DOSTEPNE WYJSCIE:\nPOLUDNIE-ARENA\nZACHOD-ARENA",
        2,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_54),
        ARENA_EXIT(DIRECTION_WEST, ROOM_ARENA_52)
    ),
    ARENA_ROOM(
        ROOM_ARENA_57,
        "DOSTEPNE WYJSCIE:\nPOLUDNIE-ARENA\nWSCHOD-ARENA",
        2,
        ARENA_EXIT(DIRECTION_SOUTH, ROOM_ARENA_55),
        ARENA_EXIT(DIRECTION_EAST, ROOM_ARENA_53)
    ),
    {
        ROOM_ENTERTAINMENT_VALLEY,
        "Dolina rozrywek",
        "JESTES W DOLINIE ROZRYWEK DOLINA CIAGNIE SIE NA POLNOC, NA WSCHODZIE\n"
        "JEST SLYSZALNY JAKIS DZIWNY  HALAS , NA ZACHODZIE ZAS \"LA LA LA LA\" \n"
        "ZAWSZE MOZESZ WROCIC SIE IDAC NA POLUDNIE ;)",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-ULICA DLUGA\n"
        "WSCHOD-BUDOWLA PELNA HALASU",
        NULL,
        NULL,
        {
            {DIRECTION_SOUTH, ROOM_LONG_STREET_WEST},
            {DIRECTION_EAST, ROOM_CONCERT_HALL}
        },
        2
    },
    {
        ROOM_CONCERT_HALL,
        "Sala koncertowa",
        "KIEDY PODSZEDLES BLIZEJ ZBARANIALES - TO SALA KONCERTOWA !!!\n"
        "WOKOLO TLUMY SLUCHAJA MUZYKI , DZIWNA TO MUZYKA - WLASCIWIE SAME SLOWA\n"
        "!!!!!!!!!NA SCIANIE JEST PLAKAT !!!!!!!!!!!!!!!",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-DOLINA ROZRYWEK\n"
        "POLNOC-TLUM\n"
        "POLUDNIE-TLUM",
        "PLAKAT",
        " NA PLAKACIE PISZE :\n"
        "20 X 98 r KONCERT LIROYA - ZAPRASZAMY WSZYSTKICH  ",
        {
            {DIRECTION_WEST, ROOM_ENTERTAINMENT_VALLEY},
            {DIRECTION_NORTH, ROOM_CROWD_NORTH},
            {DIRECTION_SOUTH, ROOM_CROWD_SOUTH},
            {DIRECTION_EAST, ROOM_CROWD_CENTRE}
        },
        4
    },
    {
        ROOM_CROWD_SOUTH,
        "Tlum",
        "NA BRZEGACH TLUM JEST MNIEJSZY , MIMO TO UCZUCIE SCISKU IRYTUJE CIE",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-TLUM\n"
        "WSCHOD-TLUM",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_CONCERT_HALL},
            {DIRECTION_EAST, ROOM_CROWD_SOUTHEAST}
        },
        2
    },
    {
        ROOM_CROWD_NORTH,
        "Tlum",
        "NA BRZEGACH TLUM JEST RZADSZY , BOISZ SIE POMYSLEC CO SIE DZIEJE W SRODKU",
        "DOSTEPNE WYJSCIA:\n"
        "POLUDNIE-TLUM\n"
        "WSCHOD-TLUM\n"
        "POLNOC-PIWIARNIA",
        NULL,
        NULL,
        {
            {DIRECTION_SOUTH, ROOM_CONCERT_HALL},
            {DIRECTION_EAST, ROOM_CROWD_NORTHEAST},
            {DIRECTION_NORTH, ROOM_BEER_HALL}
        },
        3
    },
    {
        ROOM_CROWD_CENTRE,
        "Tlum",
        "JESTES W SRODKU TLUMU A DO TEGO PRZY BALUSTRADKACH-CO ZA TLOK\n"
        "NIE MOZNA ODDYCHAC W TAKIM TLUMIE - LEPIEJ SZYBKO Z TAD IDZ",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-TLUM\n"
        "POLNOC-TLUM\n"
        "POLUDNIE-TLUM",
        NULL,
        NULL,
        {
            {DIRECTION_WEST, ROOM_CONCERT_HALL},
            {DIRECTION_NORTH, ROOM_CROWD_NORTHEAST},
            {DIRECTION_SOUTH, ROOM_CROWD_SOUTHEAST}
        },
        3
    },
    {
        ROOM_CROWD_SOUTHEAST,
        "Tlum",
        "JESTES Z BOKU ALE PRZY BALUSTRADKACH LUDZIE WPYCHAJA CIE NA TE BALUSTRADKI\n"
        "NIE MOZNA ODDYCHAC W TAKIM TLUMIE - LEPIEJ SZYBKO Z TAD IDZ",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-TLUM\n"
        "POLNOC-TLUM",
        NULL,
        NULL,
        {
            {DIRECTION_WEST, ROOM_CROWD_SOUTH},
            {DIRECTION_NORTH, ROOM_CROWD_CENTRE}
        },
        2
    },
    {
        ROOM_CROWD_NORTHEAST,
        "Tlum",
        "JESTES PRZY BALUSTRADKACH-NIE BEDE SIE ROZWODZIL JAK CI JEST CIASNO",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-TLUM\n"
        "POLUDNIE-TLUM",
        NULL,
        NULL,
        {
            {DIRECTION_WEST, ROOM_CROWD_NORTH},
            {DIRECTION_SOUTH, ROOM_CROWD_CENTRE}
        },
        2
    },
    {
        ROOM_BEER_HALL,
        "Piwiarnia",
        "JESTES W PIWIARNI - WOKOLO CIEBIE UNOSI SIE ZAPACH PIWA , TY NIE PIJASZ PIWA\n"
        "TY PIJASZ JABOLA !!! , NIE REZYGNUJAC ZE SWYCH PRZYZWYCZAJEN ROZGLADASZ SIE:\n"
        "I WIDZISZ MINI-BARMANA SPIESZACEGO SIE ABY PODAC WSZYSTKIM NAWARZONE PIWO\n"
        "I WIDZISZ GRUBASA KTORY PO WYPICIU 18 PIW WYRAZNIE MA PEWNE OBJAWY SPICIA",
        "DOSTEPNE WYJSCIA:\n"
        "WSCHOD-WEJSCIE NA ESTRADE\n"
        "POLUDNIE-TLUM",
        NULL,
        NULL,
        {
            {DIRECTION_EAST, ROOM_STAGE_ENTRANCE},
            {DIRECTION_SOUTH, ROOM_CROWD_NORTH}
        },
        2
    },
    {
        ROOM_STAGE_ENTRANCE,
        "Wejscie na scene",
        "TO JEST WEJSCIE NA SCENE NA KTOREJ TANCZY LIROY - UWAZAJ\n"
        "NA SCIANIE WISI !!!TABLICZKA!!!",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-PIWIARNIA\n"
        "WSCHOD-SCENA\n"
        "P.S-HEJ DZIECI JESLI CHCECIE ZOBACZYC TAMTEN SWIAT PODLACZCIE SIE DO 1000 WAT",
        "TABLICZKA",
        "*** NIE UPOWAZNIONYM WSTEP WZBRONIONY *** ",
        {
            {DIRECTION_WEST, ROOM_BEER_HALL},
            {DIRECTION_EAST, ROOM_STAGE_BACK}
        },
        2
    },
    {
        ROOM_STAGE_BACK,
        "Scena",
        "JESTES NA SCENIE , WLASCIWIE TO DOPIERO POCZATEK SCENY\n"
        "WLASCIWIE JESTES JESZCZE ZA KULISAMI BO WIDZOWIE CIE NIE WIDZA\n"
        "D.J PILNUJE ABY WSZYSTKO PRZEBIEGALO ZGODNIE Z PLAYBACKIEM",
        "DOSTEPNE WYJSCIA:\n"
        "ZACHOD-WEJSCIE NA SCENE\n"
        "POLUDNIE-SCENA",
        NULL,
        NULL,
        {
            {DIRECTION_WEST, ROOM_STAGE_ENTRANCE},
            {DIRECTION_SOUTH, ROOM_STAGE}
        },
        2
    },
    {
        ROOM_STAGE,
        "Scena",
        "ALL RIGHT JESTES NA SCENIE !!! NA TWOJ WIDOK OCHRONIAZE COS MAMROCZA\n"
        "TLUMY CIE PRAKTYCZNIE NIE ZAUWAZAJA BO ICH OCZY SKIEROWANE SA NA LIROYA\n"
        "GDY NAGLE WSROD TLUMU ZAUWAZASZ NIEZLA LALE,JEDNAK ONA KOCHA LIROYA :(",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-SCENA\n"
        "POLUDNIE-SRODEK SCENY",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_STAGE_BACK},
            {DIRECTION_SOUTH, ROOM_STAGE_CENTRE}
        },
        2
    },
    {
        ROOM_STAGE_CENTRE,
        "Srodek sceny",
        "LUDZIE SIE NA CIEBIE GAPIA , JESTES NA SRODKU SCENY !!! KTOS CI MOWI:\n"
        "HEY MAN IT,S COOL YEAH! . A TY NA TO: JE JE KUP KUL....",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-SCENA\n"
        "POLUDNIE-SCENA",
        NULL,
        NULL,
        {
            {DIRECTION_NORTH, ROOM_STAGE},
            {DIRECTION_SOUTH, ROOM_STAGE_END}
        },
        2
    },
    {
        ROOM_STAGE_END,
        "Scena",
        "UFFF PRZEBIEGLES PRZEZ SRODEK SCENY WIEC TREMA CIE JUZ NIE DRECZY\n"
        "DALEJ PISAC NIE MA O CZYM WIEC MOZESZ MI NASKOCZYC ",
        "DOSTEPNE WYJSCIA:\n"
        "POLNOC-SRODEK SCENY",
        NULL,
        NULL,
        {{DIRECTION_NORTH, ROOM_STAGE_CENTRE}},
        1
    },
    {
        ROOM_UNDERGROUND,
        "Podziemny pokoj treningowy",
        "ZSZEDLES NA DOL GDZIE TRENUJE SIE MEDYTUJAC\n"
        "NA SRODKU NA WIELKI MATERAC PRZEZNACZONY DO MEDYTACJI\n"
        "NA SCIANCE JEST PIEKNIUTKI PLAKAT",
        "DOSTEPNE WYJSCIE-GORA-HALA GLOWNA MUD SZKOLE ",
        "PLAKAT",
        NULL,
        {{DIRECTION_UP, ROOM_CENTRAL}},
        1
    }
};

static const WorldActor actors[] = {
    {WORLD_ACTOR_KORNIK, "KORNIK",
     "KORNIK SZUKA JAKIEGOS DRZEWA ABY COS PRZEKASIC"},
    {WORLD_ACTOR_MUCHA, "MUCHA",
     "MUCHA BZYKA SOBIE TO TU TO TAM"},
    {WORLD_ACTOR_BAKTERIA, "BAKTERIA",
     "BAKTERIA KTORA ZOBACZYLES POD MIKROSKOPEM STARA USUNAC CI SIE Z DROGI"},
    {WORLD_ACTOR_SLIMAK, "SLIMAK",
     "SLIMAK KTORY ZOSTAWIA SLUZ POWOLI SUNIE PO PODLODZE"},
    {WORLD_ACTOR_ZUK, "ZUK",
     "ZUK KTORY WIDZI CO SIE SWIECI ZWIEWA STAD"},
    {WORLD_ACTOR_KARALUCH, "KARALUCH",
     "OHYDNY KARALUCH MA OCHOTE CIE OBRZYDZIC"},
    {WORLD_ACTOR_MROWKA, "MROWKA",
     "MROWKA NIESIE TLUSTY PACZEK I SIE CIESZY"},
    {WORLD_ACTOR_PAJAK, "PAJAK",
     "PAJAK ZROBIL SIEC NA SCIANIE ARENY"},
    {WORLD_ACTOR_DZIK, "DZIK",
     "TLUSTY DZICZEK BIEGNIE SOBIE TEDY"},
    {WORLD_ACTOR_SZCZUR, "SZCZUR",
     "JEST TUTAJ SZCZUR,TAK WIELKI ZE WIEKSZEGO NIE WIDZIALES"},
    {WORLD_ACTOR_LIS, "LIS",
     "CHYTRY LIS SZUKA SPOSOBU BY CIE ZABIC"},
    {WORLD_ACTOR_KUROPATWA, "KUROPATWA",
     "KUROPATWA PO PROSTU JEST TU"},
    {WORLD_ACTOR_ZAJAC, "ZAJAC",
     "ZAJAC KICA SOBIE SPIEWAJAC \"POMYLONE MISIE\""},
    {WORLD_ACTOR_WILCZUR, "WILCZUR",
     "CZARNY WILCZUR PO KRZYWEJ SIE TOCZY (MU PIANA Z UST)"},
    {WORLD_ACTOR_ORZEL, "ORZEL",
     "ORZEL SZYBUJE W POWIETRZYU W POSZUKIWANIU OFIARY"},
    {WORLD_ACTOR_SARNA, "SARNA",
     "SARNA SKASZE SOBIE NIE ZDAJAC SOBIE SPRAWY ZE ZARAZ ZGINIE"},
    {WORLD_ACTOR_SLON, "SLON",
     "OGROMNIASTY SLON ZGNIATA WSZYSTKO CO NAPOTKA"},
    {WORLD_ACTOR_LEW, "LEW",
     "LEW - KROL ZWIERZAT WLASNIE ZABIJA NIEWINNE DZIECKO ROZWALAJAC JEGO MOZG"},
    {WORLD_ACTOR_ZYRAFA, "ZYRAFA",
     "ZYRAFA KTORA TU STOI NIE SZUKA ZACZEPKI"},
    {WORLD_ACTOR_WIELBLAD, "WIELBLAD",
     "WIELBLAD KORZYSTA Z GARBOW UZYWAJAC ICH JAKO SMIERTELNEJ BRONI"},
    {WORLD_ACTOR_STRUS, "STRUS",
     "STRUS NIE CHOWA GLOWY W PIASEK BO JEST NA BETONIE"},
    {WORLD_ACTOR_BOA, "BOA",
     "BOA DUSICIEL WLASNIE ZJADL KROWE "},
    {WORLD_ACTOR_WILK, "WILK",
     "WILK CHORY NA WSCIEKLIZNE PANOSZY SIE W OKOLICY"},
    {WORLD_ACTOR_BIZON, "BIZON",
     "NIEWINNY BIZON MORDUJE WLASNIE PUBLICZNOSC"},
    {WORLD_ACTOR_PANTERA, "PANTERA",
     "ZWINNA PANTERA NUDZI SIE POLYKAJAC RESZTKI LUDZKIEGO MIESA"},
    {WORLD_ACTOR_GLADIATOR, "GLADIATOR",
     "GLADIATOR ZDOBYWA TUTAJ KUNSZT"},
    {WORLD_ACTOR_WOJOWNIK, "WOJOWNIK",
     "WOJOWNIK GREEN PEACE MORDUJE TUTAJ BEZBRONNE LWIATKA :( "},
    {WORLD_ACTOR_TRENER, "TRENER",
     "TRENER CYRKU LAPIE ZWIERZETA NA SWOJE PRZEDSTAWIENIE"},
    {WORLD_ACTOR_JAMNIK, "JAMNIK",
     "DLUGI JAMNIK GRYZIE CI PODESZWY"},
    {WORLD_ACTOR_OWCZAREK, "OWCZAREK",
     "PUCHATY OWCZAREK WYLEGUJE SIE W SLONCU"},
    {WORLD_ACTOR_SPANIEL, "SPANIEL",
     "SPANIEL SLINI SIE AZ MILO"},
    {WORLD_ACTOR_PUDEL, "PUDEL",
     "PUDEL JE KITIKET WIEC CHYBA MU NIE PRZERWIESZ.....?"},
    {WORLD_ACTOR_PIESEK, "PIESEK",
     "PIESEK SZUKA DRZEWKA ABY ULZYC SOBIE"},
    {WORLD_ACTOR_TAKSOWKARZ, "TAKSOWKARZ",
     "TAKSOWKARZ WTARGNA TU ZE SWOJA BRYKA , I CZEKA NA KLIENTOW"},
    {WORLD_ACTOR_SPRZEDAWCA_PRECELKOW, "SPRZEDAWCA",
     "SPRZEDAWCA PRECELKOW WLASNIE SPRZEDAL OSTATNIEGO , CZYM DOPROWADZA DO SZALENSTWA LATAJACE WOKOLO NIEGO KRUKI"},
    {WORLD_ACTOR_ZAMIATACZ, "ZAMIATACZ",
     "ZAMIATACZ ULIC SPRAWIA ZE JEST TU CZYSTO JAK W CHLEWIE"},
    {WORLD_ACTOR_PIJAK, "PIJAK",
     "PIJAK TU STOI(DOBRE SOBIE) I SMIERDZI MU Z GEBY"},
    {WORLD_ACTOR_ZEBRAK, "ZEBRAK",
     "ZEBRAK UDOWADNIA PRZECHODNIOM ZE ON NAPRAWDE JEST CHORY NA AIDS"},
    {WORLD_ACTOR_GITARZYSTA, "GITARZYSTA",
     "GITARZYSTA GRA TU NA WYSOKIM CE-DUR"},
    {WORLD_ACTOR_PERKUSISTA, "PERKUSISTA",
     "PERKUSISTA TLUCZE TU NIEMILOSIERNIE (W) TALEZE I BEBNY"},
    {WORLD_ACTOR_ORGANISTA, "ORGANISTA",
     "ORGANISTA KORZYSTA Z 8 CIASIO NARAZ PODLĄCZONYCH DO SIECI"},
    {WORLD_ACTOR_LIROY, "LIROY",
     "MAGA BOSS TEJ PLANSZY - LIROY SPIEWA JEDEN ZE SWOICH KAWALKOW"},
    {WORLD_ACTOR_DZIECKO, "DZIECKO",
     "MILE DZIECKO POWTARZA NAJLEPSZE KAWALKI LIROYA"},
    {WORLD_ACTOR_WARIAT, "WARIAT",
     "WARIAT SIE CIESZY ZE NIE TYLKO ON JEST WARIATEM"},
    {WORLD_ACTOR_SLUCHACZ, "SLUCHACZ",
     "SLUCHACZ SLUCHA"},
    {WORLD_ACTOR_FAN, "FAN",
     "FAN LIROYA ZAPUSCIL SOBIE BRODKE JAK LIROY I MA PODJAR"},
    {WORLD_ACTOR_CZLOWIEK, "CZLOWIEK",
     "NORMALNY CZLOWIEK PRZYSZEDL POSLUCHAC LIROYA(DZIWNE NIE)?"},
    {WORLD_ACTOR_POLICJANT, "POLICJANT",
     "ZALANY POLICJANT STARA SIE PELNIC SWA SLUZBE"},
    {WORLD_ACTOR_OCHRONIARZ, "OCHRONIARZ",
     "OCHRONIARZ ZABIJA KAZDEGO KTO PRZEJDZIE PRZEZ BALUSTRADKI"},
    {WORLD_ACTOR_GORYL, "GORYL",
     "PRYWATNY GORYL LIROYA JE BANANA "},
    {WORLD_ACTOR_DZIADEK, "DZIADEK",
     "DZIADEK NIESTESTY NIE SKACZE DO GORY JAK KANGURY"},
    {WORLD_ACTOR_REPORTER, "REPORTER",
     "REPORTER UWAZNIE ZAPISUJE WSZYSTKIE WULGARYZMY"},
    {WORLD_ACTOR_SZCZAW, "SZCZAW",
     "PONURY SZCZAW PLANUJE ZEMSCIC SIE NA SWOJEJ TESCIOWEJ-LISCIU KLONOWYM"},
    {WORLD_ACTOR_STOKROTKA, "STOKROTKA",
     "STOKROTKA TUTAJ ROSNIE POLNA ( A NAD NIA SZUMI GEJ) "},
    {WORLD_ACTOR_KONICZYNKA, "KONICZYNKA",
     "KONICZYNKA KTORA TUTAJ JEST NIE PRZENIESIE CI SZCZESCIA"},
    {WORLD_ACTOR_MLECZ, "MLECZ",
     "MLECZ WLASNIE DOWIODL ZE EINSTEIN SIE MYLIL"},
    {WORLD_ACTOR_DMUCHAWIEC, "DMUCHAWIEC",
     "DMUCHAWIEC WLASNIE DOJRZAL DO TEGO ABY GO ZDMUCHNAC"},
    {WORLD_ACTOR_ROZA, "ROZA",
     "PRZEROSNIETA ROZA POKAZUJE KOLCE NA ZNAK IZ NIE WARTO JEJ ATAKOWAC"},
    {WORLD_ACTOR_JEZYNA, "JEZYNA",
     "TA JEZYNA W CIEMNOSCIACH WYGLADA JAK JAKIS NIEBYWALY SMOK ... "},
    {WORLD_ACTOR_OSET, "OSET",
     "KIEDYS MYSLALES ZE OSET TO LATWY DO WYRWANIA CHWAST ... MYLILES SIE"},
    {WORLD_ACTOR_AGREST, "AGREST",
     "AGREST JEST TU , CHCESZ SPROBOWAC JAK SMAKUJE ?"},
    {WORLD_ACTOR_MALINA, "MALINA",
     "MALINA JAK DZIEWCZYNA , CHOC DZIEWCZYNY NIE SA CHYBA AZ TAKIMI MUTANTAMI"},
    {WORLD_ACTOR_TRAWA, "TRAWA",
     "TRAWA NIE WYDAJE SIE TRUDNYM PRZECIWNIKIEM , LECZ NIE DAJ SIE ZWIESC"},
    {WORLD_ACTOR_DUNCAN, "DUNCAN",
     "ROLNIK DUNCAN PROBOJE ZAPANOWAC NAD TYM ZYWIOLEM I UPRAWIAC SWOJE MARCHEWKI"},
    {WORLD_ACTOR_CAGE_WEAK, "POTWOR",
     "POTWOR - CIENIAS STOI NA 1 NODZE POD SCIANA"},
    {WORLD_ACTOR_CAGE_DEXTEROUS, "POTWOR",
     "ZRECZNY POTWOR SMIGA MIEDZY SCIANAMI"},
    {WORLD_ACTOR_CAGE_RESISTANT, "POTWOR",
     "POWOLNY ACZ ODPORNY NA BOL POTWOR SPOKOJNIE LEZY POD SCIANA"},
    {WORLD_ACTOR_CAGE_STRONG, "POTWOR",
     "SILNY , NAPAKOWANY POTWOR STOI POD SCIANA"},
    {WORLD_ACTOR_CAGE_ALL, "POTWOR",
     "OGROMNY POTWOR WIDZAC MIESO RZUCA SIE NA CIEBIE"},
    {WORLD_ACTOR_POKRZYWA, "POKRZYWA",
     "MOJ BOZE , COZ TO JEST , NA TRONIE SIEDZI 20 RAZY WIEKSZA OD CIEBIE POKRZYWA"},
    {WORLD_ACTOR_STARUCH, "STARUCH",
     "W ROGU ZAUWAZASZ MALEGO WYGLODZONEGO ELFIEGO STARUCHA"},
    {WORLD_ACTOR_QUEST_MASTER, "QUEST-MASTER",
     "QUEST-MASTER NIE POSCI CIE DALEJ DOPOKI NIE KUPISZ I ROZWIAZESZ QUESTA"},
    {WORLD_ACTOR_LIVING_DOOR, "DRZWI",
     "DRZWI WYCIAGAJA SWE DREWNIANE RECE W TWYM KIERUNKU MOWIAC : NIE WPUSZCZE"}
};

static const WorldObject objects[] = {
    {WORLD_OBJECT_OLD_SWORD, "STARY",
     "W TWYM POKOJU LEZY !STARY! ZARDZEWIALY MIECZ"},
    {WORLD_OBJECT_SMALL_SHIELD, "MALA",
     "W TYM POKOJU ZNAJDUJE SIE !MALA! TARCZA"},
    {WORLD_OBJECT_BLOODY_HEART, "SERCE",
     "W TYM POKOJU ZNAJDUJE SIE ZAKRWAWIONE !SERCE!"},
    {WORLD_OBJECT_SCHOOL_DIPLOMA, "DYPLOM",
     "W TYM POKOJU ZNAJDUJE SIE !DYPLOM! MUD SZKOLY"},
    {WORLD_OBJECT_PIPE, "FAJKA", "TU LEZY !FAJKA!"}
};

const Room *world_find_room(int id)
{
    size_t index;

    for (index = 0; index < sizeof(rooms) / sizeof(rooms[0]); ++index) {
        if (rooms[index].id == id) {
            return &rooms[index];
        }
    }

    return NULL;
}

const RoomExit *world_find_exit(const Room *room, Direction direction)
{
    size_t index;

    if (room == NULL) {
        return NULL;
    }

    for (index = 0; index < room->exit_count; ++index) {
        if (room->exits[index].direction == direction) {
            return &room->exits[index];
        }
    }

    return NULL;
}

size_t world_room_count(void)
{
    return sizeof(rooms) / sizeof(rooms[0]);
}

const Room *world_room_at(size_t index)
{
    if (index >= world_room_count()) {
        return NULL;
    }
    return &rooms[index];
}

size_t world_actor_count(void)
{
    return sizeof(actors) / sizeof(actors[0]);
}

const WorldActor *world_actor_at(size_t index)
{
    if (index >= world_actor_count()) {
        return NULL;
    }
    return &actors[index];
}

size_t world_object_count(void)
{
    return sizeof(objects) / sizeof(objects[0]);
}

const WorldObject *world_object_at(size_t index)
{
    if (index >= world_object_count()) {
        return NULL;
    }
    return &objects[index];
}
