unit MONSTRA;
{ checksum = $242F }
interface

uses  crt, System;

  MAXE: Integer;
  JAMNIK: Integer;
  OWCZAREK: Integer;
  SPANIEL: Integer;
  PUDEL: Integer;
  PIESEK: Integer;
  TAKSOWKARZ: Integer;
  SPRZEDAWCA: Integer;
  ZAMIATACZ: Integer;
  PIJAK: Integer;
  ZEBRAK: Integer;
  MINIBARMAN: Integer;
  GRUBAS: Integer;
  DJ: Integer;
  PEDAL: Integer;
  PARA: Integer;
  MACIEK: Integer;
  OGOL: Integer;
  DRZWI: Integer;
  STARUCH: Integer;
  SILNY: Integer;
  procedure WSTEP;
  { Proc $0008 Entry 0:022B }
implementation
  (* BODY TODO: reconstruct from BOMBKI.EXE code disassembly.
     Linked code blocks & entries are documented in
     analysis-results\tpu_reports\MONSTRA.*.txt and analysis-results\exe_reports\exe.*.txt *)
begin
  { unit-initialization: runs once at program start }
end.
