[dosbox]
machine=svga_bridge
memsize=32

[cpu]
core=auto
cputype=pentium

[render]
frameskip=0

[sdl]
fullscreen=false
fulldouble=false
autolock=false

[mixer]
nosound=true

[dos]
ver=7.0

[autoexec]
mount c /tools/tp7
# Previous TP7 mount: /opt/tp7
mount d /workspace
d:
